spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iconique?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver 

client:
  id: admin-cli
cient: 
  secret: e7b83f44-96a7-4f59-a8a5-3cd0689d93df
keycloak:
  url: http://localhost:8088/auth/realms/master/protocol/openid-connect/token
grant: 
  type: password
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
        
        
country-url: https://restcountries.com/v3.1/all
