spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iconique?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver 

client:
  id: admin-cli
cient: 
  secret: 402b9fb3-637e-4913-82c6-847a4d352fa3
keycloak:
  url: http://localhost:8080/auth/realms/master/protocol/openid-connect/token
  usercreateurl: http://localhost:8080/auth/admin/realms/master/users
  adminuser: admin
  adminpassword: admin
grant: 
  type: password
  
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
        
        
country-url: https://restcountries.com/v3.1/all
