spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iconique?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver 
    
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
        
        
country-url: https://restcountries.com/v3.1/all
